name: Pipeline Lint

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  lint:
    name: Lint Code Base
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.6.0'

      - name: Install dependencies
        run: npm install

      - name: Read skip-tests configuration
        id: read_config
        run: |
          $skip_tests = (Get-Content skip-tests.config.json | ConvertFrom-Json).skipTests
          echo "RUN_TESTS=$skip_tests" >> $env:GITHUB_ENV

      - name: Run ESLint
        run: npm run lint

      - name: Run unit tests
        if: env.RUN_TESTS == 'true'
        run: |
          npm test || true
